package net.runelite.client.plugins.leaguesPlanker;

public enum leaguesPlankerState
{

	HANDLE_BREAK,
	TIMEOUT,
	ITERATING,
	IDLING,
	DEPOSIT_ALL_PLANKS,
	WITHDRAW_LOGS,
	OPEN_BANK,
	OUT_OF_LOGS,
	MOVING,
	CLICK_PLANK_WIDGET,
	INTERACT_SAWMILL,
	WITHDRAW_LAWS,
	WITHDRAW_RING,
	EQUIP_RING,
	TELEPORT_CRYSTAL,
	TELEPORT_BANK,
	CLOSE_BANK
}
